# Example of rump running in a container
# build: docker build -t temp/rump -f Dockerfile.example .
# run: docker run --rm temp/rump

FROM alpine:latest

RUN apk add --no-cache curl

RUN \
VERSION=0.9.3 && curl -L -o /rump \
https://github.com/stickermule/rump/releases/download/$VERSION/rump-beta-$VERSION && chmod +x /rump

ENTRYPOINT ["/rump"]
